# Generated by Django 4.0.5 on 2022-10-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(blank=True, max_length=20, null=True)),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('descn', models.CharField(blank=True, max_length=150, null=True)),
                ('tagi', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Ema', models.CharField(max_length=32)),
                ('Message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='image/')),
                ('designName', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProSeName', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=32)),
                ('AccountNumber', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MethodToPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ammount', models.FloatField()),
                ('PaymentWay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod', to='design.card')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentAccount', to='design.customer')),
            ],
        ),
    ]
