# Generated by Django 4.0.5 on 2022-10-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_mydesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(max_length=11, null=True)),
                ('mail', models.CharField(max_length=32)),
                ('Project_Type', models.CharField(max_length=40)),
                ('Time', models.FloatField()),
                ('Skills', models.CharField(max_length=50)),
                ('Budget', models.FloatField()),
                ('Company', models.CharField(max_length=32)),
                ('Country', models.CharField(max_length=32)),
            ],
        ),
    ]
