# Generated by Django 4.0.5 on 2022-10-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_profileprof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='LastName',
            new_name='PhNumber',
        ),
    ]
